version: '3'

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./go/src
        target: /go/src


  db:
    container_name: db
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - 5432:5432
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: Mmky1031!
      TZ: 'Asia/Tokyo'
