version: '3'

services:
  app:
    container_name: study_go_member_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-compose.env
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/go/src

  db:
    container_name: study_go_member_db
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - 5432:5432
    env_file:
      - docker-compose.env